[package]
name = "tauri-app"
version.workspace = true
edition.workspace = true
default-run = "tauri-app"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
shared.workspace = true
tauri = { version = "2", features = [] }
serde.workspace = true
serde_json.workspace = true

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
